name: Docker Build

on:
  push:
    branches:
    - master
    paths:
    - 'Dockerfile'
    - 'install*.sh'
    - 'debian/postinst'
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00 AM

jobs:
  docker-hub:
    name: Main Job
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dragoncomputer/dragonfire
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
