name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://dragoncomputer/dragonfire:latest
    - uses: actions/checkout@v1

    - name: Cache pip packages
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Get spaCy cache path
      id: spacy-cache
      run: |
        python3 -c "import site; print('::set-output name=dir::' + site.getsitepackages()[0] + '/en_core_web_sm')"

    - name: Cache spaCy en_core_web_sm model
      uses: actions/cache@v1
      with:
        path: ${{ steps.spacy-cache.outputs.dir }}
        key: ${{ runner.os }}-spacy-${{ hashFiles('**/debian/postinst') }}
        restore-keys: |
          ${{ runner.os }}-spacy-

    - name: Cache DeepPavlov models
      uses: actions/cache@v1
      with:
        path: ~/.deeppavlov/
        key: ${{ runner.os }}-deeppavlov-${{ hashFiles('**/debian/postinst') }}
        restore-keys: |
          ${{ runner.os }}-deeppavlov-

    - name: Install dependencies
      run: |
        sudo make dev-install-no-model
        sudo pip3 install pytest-faulthandler
        sudo apt install xvfb

    - name: Lint with flake8
      run: |
        sudo pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        sudo pip3 install pytest pytest-cov codecov
        xvfb-run --auto-servernum python3 -m pytest --cov=dragonfire/ --capture=sys --disable-pytest-warnings -vv
        # send the code coverage report to Codeconv
        codecov --token=${{ secrets.CODECOV_TOKEN }}
